// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetPassword(arg1, arg2) {
  return window['go']['main']['App']['GetPassword'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetViewerSessionIds() {
  return window['go']['main']['App']['GetViewerSessionIds']();
}

export function HasPassword(arg1, arg2) {
  return window['go']['main']['App']['HasPassword'](arg1, arg2);
}

export function IsRDPClientInstalled() {
  return window['go']['main']['App']['IsRDPClientInstalled']();
}

export function IsViewerConnected() {
  return window['go']['main']['App']['IsViewerConnected']();
}

export function IsViewerSessionConnected(arg1) {
  return window['go']['main']['App']['IsViewerSessionConnected'](arg1);
}

export function LaunchRDP(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchRDP'](arg1, arg2, arg3);
}

export function ListInstances(arg1) {
  return window['go']['main']['App']['ListInstances'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function ListWindowsInstances(arg1) {
  return window['go']['main']['App']['ListWindowsInstances'](arg1);
}

export function LoginWithGcloud() {
  return window['go']['main']['App']['LoginWithGcloud']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ResetWindowsPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResetWindowsPassword'](arg1, arg2, arg3, arg4);
}

export function SetViewerQuality(arg1) {
  return window['go']['main']['App']['SetViewerQuality'](arg1);
}

export function SetViewerResolution(arg1, arg2) {
  return window['go']['main']['App']['SetViewerResolution'](arg1, arg2);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function StartTunnel(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3);
}

export function StartViewer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartViewer'](arg1, arg2, arg3);
}

export function StartViewerDirect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartViewerDirect'](arg1, arg2, arg3, arg4);
}

export function StartViewerSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartViewerSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopAllTunnels() {
  return window['go']['main']['App']['StopAllTunnels']();
}

export function StopAllViewerSessions() {
  return window['go']['main']['App']['StopAllViewerSessions']();
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function StopViewer() {
  return window['go']['main']['App']['StopViewer']();
}

export function StopViewerSession(arg1) {
  return window['go']['main']['App']['StopViewerSession'](arg1);
}

export function StorePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorePassword'](arg1, arg2, arg3);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ViewerKeyboard(arg1, arg2) {
  return window['go']['main']['App']['ViewerKeyboard'](arg1, arg2);
}

export function ViewerMouseClick(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ViewerMouseClick'](arg1, arg2, arg3, arg4);
}

export function ViewerMouseMove(arg1, arg2) {
  return window['go']['main']['App']['ViewerMouseMove'](arg1, arg2);
}

export function ViewerMouseWheel(arg1) {
  return window['go']['main']['App']['ViewerMouseWheel'](arg1);
}

export function ViewerSessionKeyboard(arg1, arg2, arg3) {
  return window['go']['main']['App']['ViewerSessionKeyboard'](arg1, arg2, arg3);
}

export function ViewerSessionMouseClick(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ViewerSessionMouseClick'](arg1, arg2, arg3, arg4, arg5);
}

export function ViewerSessionMouseMove(arg1, arg2, arg3) {
  return window['go']['main']['App']['ViewerSessionMouseMove'](arg1, arg2, arg3);
}

export function ViewerSessionMouseWheel(arg1, arg2) {
  return window['go']['main']['App']['ViewerSessionMouseWheel'](arg1, arg2);
}
