// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {gcp} from '../models';

export function AddConnection(arg1:config.Connection):Promise<void>;

export function Connect(arg1:config.Connection):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function GetAuthStatus():Promise<Record<string, any>>;

export function GetConnections():Promise<Array<config.Connection>>;

export function GetPassword(arg1:string,arg2:string):Promise<string>;

export function GetSettings():Promise<config.AppSettings>;

export function GetViewerSessionIds():Promise<Array<string>>;

export function HasPassword(arg1:string,arg2:string):Promise<boolean>;

export function IsRDPClientInstalled():Promise<boolean>;

export function IsViewerConnected():Promise<boolean>;

export function IsViewerSessionConnected(arg1:string):Promise<boolean>;

export function LaunchRDP(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ListInstances(arg1:string):Promise<Array<gcp.Instance>>;

export function ListProjects():Promise<Array<gcp.Project>>;

export function ListTunnels():Promise<Array<Record<string, any>>>;

export function ListWindowsInstances(arg1:string):Promise<Array<gcp.Instance>>;

export function LoginWithGcloud():Promise<void>;

export function Logout():Promise<void>;

export function ResetWindowsPassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetViewerQuality(arg1:number):Promise<void>;

export function SetViewerResolution(arg1:number,arg2:number):Promise<void>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function StartTunnel(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function StartViewer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartViewerDirect(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function StartViewerSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<void>;

export function StopAllTunnels():Promise<void>;

export function StopAllViewerSessions():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function StopViewer():Promise<void>;

export function StopViewerSession(arg1:string):Promise<void>;

export function StorePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateConnection(arg1:config.Connection):Promise<void>;

export function UpdateSettings(arg1:config.AppSettings):Promise<void>;

export function ViewerKeyboard(arg1:number,arg2:boolean):Promise<void>;

export function ViewerMouseClick(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function ViewerMouseMove(arg1:number,arg2:number):Promise<void>;

export function ViewerMouseWheel(arg1:number):Promise<void>;

export function ViewerSessionKeyboard(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function ViewerSessionMouseClick(arg1:string,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function ViewerSessionMouseMove(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ViewerSessionMouseWheel(arg1:string,arg2:number):Promise<void>;
